# -*- coding: utf-8 -*-
"""승률.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gyS2Fy-z5OeoyURQzzmgwXe9Ep1ujnZW
"""

#두산 득실점
OB_RUN = 109
OB_R = 87
#넥센 득실점
WO_RUN = 113
WO_R = 84
#삼성 득실점
SS_RUN = 73
SS_R = 95
#SK 득실점
SK_RUN = 104
SK_R = 101
#NC 득실점
NC_RUN = 91
NC_R = 85
#LG 득실점
LG_RUN = 79
LG_R = 81
#한화 득실점
HH_RUN = 83
HH_R = 103
#롯데 득실점
LT_RUN = 91
LT_R = 93
#KIA 득실점
HT_RUN = 66
HT_R =  89
#KT 득실점
KT_RUN = 74
KT_R = 92

#피타고리안 승률 계산의 쓰이는 X 지수값 구하기 ex) (Y)**X

x_OB = ((OB_RUN + OB_R)/18) ** 0.287
x_WO = ((WO_RUN + WO_R)/18) ** 0.287
x_SS = ((SS_RUN + SS_R)/20) ** 0.287
x_SK = ((SK_RUN + SK_R)/18) ** 0.287
x_NC = ((NC_RUN + NC_R)/20) ** 0.287
x_LG = ((LG_RUN + LG_R)/20) ** 0.287
x_HH = ((HH_RUN + HH_R)/20) ** 0.287
x_LT = ((LT_RUN + LT_R)/18) ** 0.287
x_HT = ((HT_RUN + HT_R)/19) ** 0.287
x_KT = ((KT_RUN + KT_R)/19) ** 0.287

#피타고리안 승률 계산 

y_OB = (OB_RUN)**x_OB / ((OB_RUN)**x_OB + (OB_R)**x_OB)
y_WO = (WO_RUN)**x_WO / ((WO_RUN)**x_WO + (WO_R)**x_WO)
y_SS = (SS_RUN)**x_SS / ((SS_RUN)**x_SS + (SS_R)**x_SS)
y_SK = (SK_RUN)**x_SK / ((SK_RUN)**x_SK + (SK_R)**x_SK)
y_NC = (NC_RUN)**x_NC / ((NC_RUN)**x_NC + (NC_R)**x_NC)
y_LG = (LG_RUN)**x_LG / ((LG_RUN)**x_LG + (LG_R)**x_LG)
y_HH = (HH_RUN)**x_HH / ((HH_RUN)**x_HH + (HH_R)**x_HH)
y_LT = (LT_RUN)**x_LT / ((LT_RUN)**x_LT + (LT_R)**x_LT)
y_HT = (HT_RUN)**x_HT / ((HT_RUN)**x_HT + (HT_R)**x_HT)
y_KT = (KT_RUN)**x_KT / ((KT_RUN)**x_KT + (KT_R)**x_KT)

print("OB의 승률 : ",round(y_OB,3))
print("WO의 승률 : ",round(y_WO,3))
print("SS의 승률 : ",round(y_SS,3))
print("SK의 승률 : ",round(y_SK,3))
print("NC의 승률 : ",round(y_NC,3))
print("LG의 승률 : ",round(y_LG,3))
print("HH의 승률 : ",round(y_HH,3))
print("LT의 승률 : ",round(y_LT,3))
print("HT의 승률 : ",round(y_HT,3))
print("KT의 승률 : ",round(y_KT,3))

import pandas as pd 
import numpy as np

total_pv = pd.DataFrame({'T_ID' : ['OB','WO','SS','SK','NC','LG','HH','LT','HT','KT'], 'PV' : [0.61,0.643,0.381,0.515,0.532,0.489,0.399,0.489,0.367,0.4]})

total_pv = total_pv.sort_values(by='PV',ascending=False)

total_pv

